### ISSUE TITLE
Publishing on Quarkus Registry

### ISSUE THREAD

**Issue by mcollovati** [vaadin/quarkus#105]
Quarkus provides an [extension registry](https://quarkus.io/guides/extension-registry-user) where also non-platform extensions can be published, and the easily discovered by browsing the dedicate [web page](https://quarkus.io/extensions/) or using developer tools.

Quarkus also provides a [web tool](https://code.quarkus.io/), similar to start.vaadin.com, that allows to quickly set up an application by selecting the needed extension from the list of artifacts published on the registry.

The [publishing process](https://quarkus.io/guides/writing-extensions#publish-your-extension-in-registry-quarkus-io) seems straightforward, and it should be done only once. After that, a scheduled job will check Maven Central for new versions and update the Quarkus Extension Registry

**Comment by mcollovati** [comment]
Direct link to the Quarkus Ecosystem CI [README](https://github.com/quarkusio/quarkus-ecosystem-ci/blob/main/README.adoc), with instructions to setup a Github Action to validate the extension at every Quarkus release

**Comment by mcollovati** [comment]
For the automatic builds against the latest Quarkus version, it seems like it is possible to define different target branches in the metadata with the `alternatives` key, as in the following example

https://github.com/quarkusio/quarkus-ecosystem-ci/blob/6618e668d099695dd93ffef673a07c38373181c5/kogito-quarkus/info.yaml#L1-L8

**Comment by gastaldi** [comment]
Welcome aboard! 

![image](https://user-images.githubusercontent.com/54133/235176949-2d97945b-06e0-4165-b403-92e6eb4b5b48.png)
