### ISSUE TITLE
Implement custom CDI scopes for Quarkus

### ISSUE THREAD

**Issue by caalador** [vaadin/quarkus#13]
Implement custom CDI scopes for Quarkus.

Implemented scopes should contain at least:
- [x] RouteScoped
- [x] RouteScopeOwner
- [x] UIScoped
- [x] VaadinServiceScoped
- [x] VaadinSessionScoped

Custom Scopes need to be registered in the VaadinQuarkusProcessor in `@BuildStep`s

**Comment by denis-anisimov** [comment]
Only normal scopes are currently supported by Quarkus,
I made a ticket about pseudo scopes : https://github.com/quarkusio/quarkus/issues/19725
It's fixed but I don't know at which point we will be able to use it in some quarkus release.
Once quarkus with fix is released the pseudo scopes can be implemented on top of normal scopes (the impl can be done using quite simple wrapper but the tests need to be ported from CDI , the tests for normal scope will work only for beans and not for Vaadin components).

**Comment by denis-anisimov** [comment]
https://github.com/vaadin/quarkus/pull/25 PR add _only_ normal scopes.
Pseudo-scopes don't work in quarkus at the moment.
I will make another ticket to add pseudo-scopes once they are supported by existing Quarkus release.
