### ISSUE TITLE
Dead guide link in extension metadata

### ISSUE THREAD

**Issue by holly-cummins** [vaadin/quarkus#161]
Dead link: https://vaadin.com/docs/latest/integrations/quarkus

I'm not sure if the best fix is an updated link, or ... ?

To see one place where the guide link is used, see  https://quarkus.io/extensions/com.vaadin/vaadin-quarkus-extension/

**Comment by mstahv** [comment]
@jouni Redirects!!! https://vaadin.com/docs/latest/flow/integrations/quarkus

**Comment by mcollovati** [comment]
Thank you very much for reporting. We will fix it as soon as possible

**Comment by jouni** [comment]
I just merged fixes to the redirects. I’m not sure how long it takes for them to get deployed and get effective, though.
