### ISSUE TITLE
Supporting Vaadin add-ons

### ISSUE THREAD

**Issue by pleku** [vaadin/quarkus#17]
> If you can’t modify the dependency, you can still index it by adding quarkus.index-dependency entries to your application.properties:

```
quarkus.index-dependency.<name>.group-id=
quarkus.index-dependency.<name>.artifact-id=
quarkus.index-dependency.<name>.classifier=(this one is optional)
```
### Acceptance Criteria
- [x] Document the necessary steps to make any Vaadin add-on compatible with Quarkus on the application project 
- [x] Add an integration test to the Quarkus project that uses an add-on without yandex index but it still works as it is configured in the project like ^

**Comment by caalador** [comment]
Documentation exists, but the `application.properties` should be expanded with better example.
