### ISSUE TITLE
Use native Quarkus Websockets

### ISSUE THREAD

**Issue by miguelatvaadin** [vaadin/quarkus#5]
Enable atmosphere to use Quarkus websockets, as they are not jsr356 compliant anymore since 10.whatever version of Quarkus.

This results in Devmode Gizmo not working (it depends on websockets for live reload) and Push falling back to long polling.

### Actual behavior
Atmosphere complains and says there is no websocket implementation available

### Expected behavior
Atmosphere uses Quarkus native websockets

#### Hint
Add a new Quarkus specific class to https://github.com/vaadin/atmosphere/tree/master/modules/runtime/src/main/java/org/atmosphere/container

**Comment by mcollovati** [comment]
Quarkus documentation states that "The Quarkus WebSocket implementation is an implementation of Jakarta Websockets", so Atmosphere should work with JSR356Endpoint; maybe something has changed in the meanwhile.

Currently there are two issues with PUSH on Quarkus:
* Quarkus websocket feature is enabled only if classes related to websocket are found; in detail at least a class implementing `javax.websocket.server.ServerApplicationConfig`, extending `javax.websocket.Endpoint` or annotated with `javax.websocket.server.ServerEndpoint`.
 More details on https://github.com/urosporo/vaadin-quarkus-extension-parent/pull/11 and related issue
* The Vert.x handler that processes websocket ugrade request has no knowledge about Undertow HTTP session, so Flow PushHandler always sends "Session expired" notification and the browser tried to reconnect again and again with no success.

As a temporary solution we can add to the extension a class to enable websocket deployment and a build step that will produce a build item with a modified version of `VertxWebSocketHandler` that handles only Vaadin PUSH request and tries to attach the HTTP session to the exchange of the upgrade request.
