### ISSUE TITLE
Build against development builds of Quarkus to be always ready for the next release

### ISSUE THREAD

**Issue by mstahv** [vaadin/quarkus#52]
Instructions:

https://github.com/quarkusio/quarkus-ecosystem-ci

**Comment by mcollovati** [comment]
Quarkus ecosystem integration has been implemented.
Now there is a daily job, triggered by a Quarkus, that runs a validation job for both main and 1.1 branches.
Issues #108 and #109 are re-opened if the validation fails and closed again upon successful builds.
