### ISSUE TITLE
Update Quarkus documentation after fixing Push functionality

### ISSUE THREAD

**Issue by mshabarov** [vaadin/quarkus#70]
Update Quarkus docs to not mention Push websockets as not working after applying of this change 
https://github.com/vaadin/quarkus/pull/69.

Quarkus docs to be updated:
https://vaadin.com/docs/latest/flow/integrations/quarkus/#quarkus.vaadin.limitations

**Comment by mcollovati** [comment]
Created the [PR](https://github.com/vaadin/docs/pull/1221) on vaadin/docs repo
